### PR TITLE
feat: update iOS plugin version

### PR DESCRIPTION
**Pull request by dnshi**
# Summary
- Update Amplitude iOS
- Add Analytics Connector to the plugin

### CODE REVIEW

**Comment by dnshi** [comment]
@bgiori It is a direct copy of the iOS SDK and the analytics connector, but I add/update 3 `.h` files for Swift:
- Assets/Plugins/iOS/Amplitude/AnalyticsConnector.h
- Assets/Plugins/iOS/Amplitude/EventBridge.h
- Assets/Plugins/iOS/Amplitude/IdentityStore.h

The analytics connector is a dependency but I copy the files into this project. Adding `.h` to import Swift into Objc. The main effort in this PR is the above three `.h` files, and the build is succeeded on the Xcode.  


image

Please let me know if I miss anything. Thanks!

**Comment by bgiori** [comment]
Would we be able to test that both SDKs communicate with each other in a unity iOS app?

**Comment by dnshi** [comment]
Unity iOS part is same as iOS SDK. Currently, Unity SDK is a wrapper for iOS SDK and Android SDK. The Unity methods written in C# are calling iOS SDK or Android SDK. We will build C# SDK next and then replace the existing Unity SDK.

**Review by bgiori — APPROVED** [review]
👍

**Review by qingzhuozhen — APPROVED** [review]

**Pull request merged**
