### PR TITLE
Create codacy-analysis.yml

### PR DESCRIPTION
**Pull request by qingzhuozhen**
coday workflow test

### CODE REVIEW

**Comment by haoliu-amp** [comment]
What's this for?

**Comment by qingzhuozhen** [comment]
@haoliu-amp this is trying another code scan plugin since code ql didn't support some languages like objective-c. For now just try and check the result.

**Comment by haoliu-amp** [comment]
Have you checked with Rupa if we can use this?

**Comment by qingzhuozhen** [comment]
@haoliu-amp this is recommended by the github people in trial session. One of the todo items is try some alternative plugin when code ql doesn't work. I can run by Rupa again after go over the results of scanning.

**Review by haoliu-amp — APPROVED** [review]

**Pull request closed without merging**
