### PR TITLE
Enabling tvOS compile on .h/.m files, updating AmplitudePostProcessor.cs

### PR DESCRIPTION
**Pull request by keerthik**
This commit trivially enables Amplitude to work on tvOS builds in addition to existing targets, and has been tested with our sample application and production application in beta.

### CODE REVIEW

**Comment by dantetam** [comment]
Hello @keerthik ,

Thank you for providing this PR. There may be some changes on our end we will have to complete. We plan to integrate and do our own testing and bug fixes within 2-3 weeks. We may or may not keep EventExplorer, depends on our product need.

I'll definitely start by testing out this branch.

Dante

**Comment by keerthik** [comment]
Thank you, we are targeting release of our Unity project using Amplitude to tvOS next month, happy to assist with the merge or field testing. In the meantime we plan to proceed using my fork of this repo.

**Comment by keerthik** [comment]
Just wanted to bump this pull request with an update that we have been able to receive analytics from tvOS devices without issue, reporting OS version, creating a unique device id, and recording user events without a problem.

**Comment by keerthik** [comment]
I see this issue was closed along with rejection — does the new release from the original library compile work on tvOS with the above tasks (record device id, map to OS version, track user events sent from Unity)? Or should I continue using my fork for tvOS Unity builds?

**Comment by dnshi** [comment]
Thanks for the PR. I will create a separate PR for the change.

**Pull request closed without merging**
